### ISSUE TITLE
add a screenshot

### ISSUE THREAD

**Issue by dridk** [philipeachille/typesense-ui#1]
Could you add a screenshot in the readme ?

**Comment by philipeachille** [comment]
Hi! yea, will do.

**Comment by philipeachille** [comment]
I will have to create "senseful" demo content also, so this will take a little longer, sorry. It's probably quicker to connect this repo/ui to your instance

**Comment by philipeachille** [comment]
screenshot added

**Comment by philipeachille** [comment]
demo content added. Simply clone or download the repo and open "typesense-ui.html". Hope you find the UI useful.

**Comment by dridk** [comment]
thank you  !
